version: '2'
services:
  tsamnode:
    image: oracle/tsam
    command: /bin/bash -c "while true; do foo; sleep 2; done"
    ports:
      - "7001:7001"
  ora_db:
    image: oracle/database:11.2.0.2-xe
    shm_size: 1g
    volumes:
      - "~/dockerDBtest:/u01/app/oracle/oradata"
  sanfrancisco:
    hostname: sanfrancisco
    build: 
        context: .
        dockerfile: Dockerfile.bankapp.shm
        args:
          site: sanfrancisco
          siteu: SANFRANCISCO
    command: /bin/bash -x boot.sh
  chicago:
    hostname: chicago
    build: 
        context: .
        dockerfile: Dockerfile.bankapp.shm
        args:
          site: chicago
          siteu: CHICAGO
    command: /bin/bash -x boot.sh
  newyork:
    hostname: newyork
    build: 
        context: .
        dockerfile: Dockerfile.bankapp.shm
        args:
          site: newyork
          siteu: NEWYORK
    command: /bin/bash -x boot.sh
  broker:
    hostname: broker
    build:
        context: .   
        dockerfile: Dockerfile.brokerapp
        args:
          site: SITE1
    command: /bin/bash -x /home/oracle/sleep.sh &> sleep.log
  brokerbackup:
    hostname: brokerbackup
    build:
        context: .   
        dockerfile: Dockerfile.brokerapp
        args:
          site: SITE2
    command: /bin/bash -x /home/oracle/sleep.sh &> sleep.log
